name: asset_tracker
description: "A simple asset tracking app with QR scanning."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.1.1
  http: ^1.2.0
  intl: ^0.19.0
  sqflite: ^2.3.2
  path: ^1.9.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/sk_new_logo.jpeg

flutter_icons:
  image_path: "assets/sk_new_logo.jpeg"
  android: true
  ios: true